name: flutter_hrm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_reactive_ble: ^5.0.2
  permission_handler: ^10.0.0
  freezed_annotation: ^2.0.3
  rxdart: ^0.27.4
  flutter_bloc: ^8.0.1
  stream_bloc: ^0.5.1
  provider: ^6.0.3
  flutter_map: ^1.1.1
  geolocator: ^9.0.0
  latlong2: ^0.8.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  json_annotation: ^4.5.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
flutter:
  uses-material-design: true
