// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFuUldzO2t6OBL8tM8M0yGaigk3P9svwc',
    appId: '1:302436165721:web:09816e3ab38a68a0262948',
    messagingSenderId: '302436165721',
    projectId: 'flutterhrm',
    authDomain: 'flutterhrm.firebaseapp.com',
    storageBucket: 'flutterhrm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXzYYObSlt3NDDnrxArG3HdxlaN8GjPg',
    appId: '1:302436165721:android:c9f9830f5f0052e4262948',
    messagingSenderId: '302436165721',
    projectId: 'flutterhrm',
    storageBucket: 'flutterhrm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCideycuDUUlSEvY7Pvk8J_GvKzWUs63dU',
    appId: '1:302436165721:ios:19d974841f9f84e9262948',
    messagingSenderId: '302436165721',
    projectId: 'flutterhrm',
    storageBucket: 'flutterhrm.appspot.com',
    iosClientId: '302436165721-rlh03mnd1ie35nib9t3aicfdafn6obuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCideycuDUUlSEvY7Pvk8J_GvKzWUs63dU',
    appId: '1:302436165721:ios:19d974841f9f84e9262948',
    messagingSenderId: '302436165721',
    projectId: 'flutterhrm',
    storageBucket: 'flutterhrm.appspot.com',
    iosClientId: '302436165721-rlh03mnd1ie35nib9t3aicfdafn6obuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHrm',
  );
}
